# LLM Model Configuration
model:
  default_selection: "hf.co/unsloth/Qwen3.5-35B-A3B-GGUF:Q6_K"
  models:
    # https://unsloth.ai/docs/models/qwen3.5#qwen3.5-35b-a3b
    - name: "hf.co/unsloth/Qwen3.5-35B-A3B-GGUF:Q6_K"
      temperature: 1.0
      max_tokens_context: 200000 
      max_tokens_output: 32000
    # https://unsloth.ai/docs/models/qwen3.5#qwen3.5-small-0.8b-2b-4b-9b
    - name: "hf.co/unsloth/Qwen3.5-0.8B-GGUF:Q6_K"
      temperature: 1.0
      max_tokens_context: 16000
      max_tokens_output: 20248

# OpenAI API Configuration for Ollama
openai:
  base_url: "http://localhost:11434/v1"
  api_key: "ollama" # Dummy value, Ollama does not require an actual API key

# Chat Configuration
chat:
  default_mode: true
  app_name: "AI Chat"

# Logging Configuration
logging:
  log_file: "chainlit_logs.log"
  log_level: "INFO"

# Defaults
default_ollama_max_tokens: 4096
default_max_tokens_output: 1024
default_temperature: 0.7

# Decrease max_tokens_context by this value to account for prompt overhead and unprecise token counting.
# We use tiktokens default encoding for estimation, which might differ from the actual model encoding.
context_token_buffer: 2048

# File format whitelist for document uploads
file_format_whitelist:
  - ".txt"
  - ".csv"
  - ".py"
  - ".md"
  - ".Rmd"
  - ".rmd"
  - ".RMD"
  - ".r"
  - ".R"

